# Generated by Django 4.1.5 on 2023-01-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='language',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='lastname',
        ),
    ]
